version: '3.8'

services:
  keycloak:
    build: .
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./themes:/opt/keycloak/themes
      - ./providers:/opt/keycloak/providers
      - ./conf:/opt/keycloak/conf
      - keycloak_data:/opt/keycloak/data
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: keycloak-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  keycloak_data:
  mysql_data:
