apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8082  # External port
      targetPort: 8082  # Port your container is listening on
  type: LoadBalancer  # Change to "NodePort" if not using a cloud provider
