apiVersion: v1
kind: Service
metadata:
  name: keycloak-mysql
spec:
  selector:
    app: keycloak-mysql
  ports:
    - protocol: TCP
      port: 3306  # External port
      targetPort: 3306  # Port your container is listening on
  type: LoadBalancer  # Change to "NodePort" if not using a cloud provider
